apiVersion: apps/v1
kind: Deployment
metadata:
  name: Screeningseatmanagement
  labels:
    app: Screeningseatmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Screeningseatmanagement
  template:
    metadata:
      labels:
        app: Screeningseatmanagement
    spec:
      containers:
        - name: Screeningseatmanagement
          image: username/Screeningseatmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5