apiVersion: v1
kind: Service
metadata:
  name: Screeningseatmanagement
  labels:
    app: Screeningseatmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Screeningseatmanagement